chain:
- gemini_2_5_flash
- gemini_2_5_flash_lite
- gemini_3_flash
data_path: ./data
language: Hungarian
profiles:
  gemini_2_5_flash:
    api_key_name: gemini
    model: gemini-2.5-flash
    provider: gemini
  gemini_2_5_flash_lite:
    api_key_name: gemini
    model: gemini-2.5-flash-lite
    provider: gemini
  gemini_3_flash:
    api_key_name: gemini
    model: gemini-3-flash-preview
    provider: gemini
